meta_product_name: "Yummi"
meta_title: "yummi - Eat local food, prepared with love"
meta_description: "Yummi connects food lovers who want to share their passion and live a unique experience."
meta_image: "YummiV4.png" # should exist in `app/assets/images/`
twitter_account: "@yummifood"
